### ISSUE TITLE
Make Dynamic Arrays generic, fix miscellaneous issues.

### ISSUE THREAD

**Issue by guiomard** [JoshuaLeeGMIT/mulib#5]
See #4 comments.

**Comment by JoshuaLeeGMIT** [comment]
Sorry about the confusion there Gavin. I force pushed to clean up the history using a stale branch and messed it up there for a few minutes. You might need to clone the repo fresh.

Anyway, I reckon the best thing is to fix the issues individually in the smallest commits possible, seems that's what is looked at.

**Comment by guiomard** [comment]
No problem, and I was thinking the same thing. Thanks for the heads up.

**Comment by JoshuaLeeGMIT** [comment]
I didn't notice you had a branch for this Gavin, sorry!

Just a few things I noticed while building it:

- Need to `#include <string.h` for `memcpy()`
- We haven't allocated memory for `arrary->array` in `mu_arr_new()`
- `mu_arr_free()` should be `void`, not return a `void *`

Just small things really, should be good for a merge request once rebased.
